using Domain.Entities;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Persistence.EF
{
    public class ApplicationContext : IdentityDbContext<User>
    {
        public DbSet<Category> Categories { get; set; }
        public DbSet<Characteristic> Characteristics { get; set; }
        public DbSet<ProductPhoto> ProductPhotos { get; set; }
        public DbSet<CategoryPhoto> CategoryPhotos { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Producer> Producers { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<IPAdress> BlackIps { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }

        public ApplicationContext(DbContextOptions<ApplicationContext> options)
            : base(options)
        {
            //Database.EnsureDeleted();
            //Database.EnsureCreated();
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<CategoryPhoto>().HasData(new CategoryPhoto[]
            {
                new CategoryPhoto { Id = 1, Path = "https://media.istockphoto.com/vectors/laptop-icon-in-flat-style-vector-for-app-ui-websites-black-icon-vector-id1148406082?k=20&m=1148406082&s=170667a&w=0&h=j3IbLZYqWXQpfafNd4LEZzVLp-5qjMz_RjBZaMdNOnw=" },
                new CategoryPhoto { Id = 2, Path = "https://user-images.githubusercontent.com/68688805/120937883-4af1a580-c725-11eb-8a0f-9f02dc5fb9a5.png" },
                new CategoryPhoto { Id = 3, Path = "https://cdn.iconscout.com/icon/free/png-256/monitor-2378451-1983777.png" },
                new CategoryPhoto { Id = 4, Path = "https://media.istockphoto.com/vectors/smartphone-icon-silhouette-on-white-background-vector-id1045395492?k=20&m=1045395492&s=170667a&w=0&h=zSObMNkrv2IW1SJrw-mA24l9SFMBk6RHLwTW4UwKc10=" }
            });

            builder.Entity<Category>().HasData(new Category[]
            {
                new Category { Id = 1, Name = "Ноутбуки та планшети", CategoryPhotoId = 1},
                new Category { Id = 2, Name = "Комплектуючі для ПК", CategoryPhotoId = 2},
                new Category { Id = 3, Name = "Комп'ютерна техніка", CategoryPhotoId = 3},
                new Category { Id = 4, Name = "Смартфони та гаджети", CategoryPhotoId = 4}
            });

            builder.Entity<SubCategory>().HasData(new SubCategory[]
            {
                new SubCategory { Id = 1, Name = "Ноутбуки", CategoryId = 1 },
                new SubCategory { Id = 2, Name = "Планшети", CategoryId = 1 },
                new SubCategory { Id = 3, Name = "Сумки та чохли для ноутбуків", CategoryId = 1 },
                new SubCategory { Id = 4, Name = "Процесори", CategoryId = 2 },
                new SubCategory { Id = 5, Name = "Материнські плати", CategoryId = 2 },
                new SubCategory { Id = 6, Name = "Відеокарти", CategoryId = 2 },
                new SubCategory { Id = 7, Name = "Модулі пам'яті", CategoryId = 2 },
                new SubCategory { Id = 8, Name = "Монітори", CategoryId = 3 },
                new SubCategory { Id = 9, Name = "Клавітури та комплекти", CategoryId = 3 },
                new SubCategory { Id = 10, Name = "Миші та трекболи", CategoryId = 3 },
                new SubCategory { Id = 11, Name = "Смартфони", CategoryId = 4 },
                new SubCategory { Id = 12, Name = "Мобільні телефони", CategoryId = 4 },
                new SubCategory { Id = 13, Name = "Кабелі та адаптери для передавання даних", CategoryId = 4 }
            });

            builder.Entity<Producer>().HasData(new Producer[]
            {
                new Producer { Id = 1, Name = "ACER" },
                new Producer { Id = 2, Name = "HP" },
                new Producer { Id = 3, Name = "LENOVO" },
                new Producer { Id = 4, Name = "DELL" },
                new Producer { Id = 5, Name = "APPLE" },
                new Producer { Id = 6, Name = "MICROSOFT" },
                new Producer { Id = 7, Name = "SAMSUNG" },
                new Producer { Id = 8, Name = "PRESTIGIO" },
                new Producer { Id = 9, Name = "TUCANO" },
                new Producer { Id = 10, Name = "CONTINENT" },
                new Producer { Id = 11, Name = "PORTO" },
                new Producer { Id = 12, Name = "CASE" },
                new Producer { Id = 13, Name = "AMD" },
                new Producer { Id = 14, Name = "INTEL" },
                new Producer { Id = 15, Name = "ASUS" },
                new Producer { Id = 16, Name = "GIGABYTE" },
                new Producer { Id = 17, Name = "AORUS" },
                new Producer { Id = 18, Name = "PALIT" },
                new Producer { Id = 19, Name = "MSI" },
                new Producer { Id = 20, Name = "HYPERX" },
                new Producer { Id = 21, Name = "KINGSTON" },
                new Producer { Id = 22, Name = "PHILIPS" },
                new Producer { Id = 23, Name = "A4TECH" },
                new Producer { Id = 24, Name = "LOGITECH" },
                new Producer { Id = 25, Name = "XIAOMI" },
                new Producer { Id = 26, Name = "ZTE" },
                new Producer { Id = 27, Name = "NOKIA" },
                new Producer { Id = 28, Name = "ATCOM" },
                new Producer { Id = 29, Name = "BASEUS" }
            });

            builder.Entity<Product>().HasData(new Product[]
            {
                new Product { Id = 1, Name = "Ноутбук ACER Swift 5 SF514-55TA-75YH Mist Green (NX.A6SEU.00A)", Price = 39_999, ProducerId = 1, CategoryId = 1, SubCategoryId = 1 },
                new Product { Id = 2, Name = "Ноутбук HP 14s-fq0029ur Natural Silver (24C05EA)", Price = 16_899, ProducerId = 2, CategoryId = 1, SubCategoryId = 1},
                new Product { Id = 3, Name = "Ноутбук LENOVO ThinkPad X1 Fold Gen 1 Black (20RL0016RT)", Price = 99_036, ProducerId = 3, CategoryId = 1, SubCategoryId = 1},
                new Product { Id = 4, Name = "Ноутбук HP Pavilion Gaming 16-a0017ua Shadow Black (423R2EA)", Price = 32_599, ProducerId = 2, CategoryId = 1, SubCategoryId = 1},
                new Product { Id = 5, Name = "Ноутбук DELL Latitude 5420 Titan Gray (N015L542014UA_UBU)", Price = 35_097, ProducerId = 4, CategoryId = 1, SubCategoryId = 1},
                new Product { Id = 6, Name = "Планшет APPLE iPad Air 3 Wi-Fi 4G 64GB Gold (MV0F2RK/A)", Price = 17_395, ProducerId = 5, CategoryId = 1, SubCategoryId = 2},
                new Product { Id = 7, Name = "Планшет MICROSOFT Surface Pro 7 8/256GB Platinum (PUV-00001)", Price = 25_048, ProducerId = 6, CategoryId = 1, SubCategoryId = 2},
                new Product { Id = 8, Name = "Планшет SAMSUNG Galaxy Tab S7 FE LTE 4/64GB Mystic Pink (SM-T735NLIASEK)", Price = 16_999, ProducerId = 7, CategoryId = 1, SubCategoryId = 2},
                new Product { Id = 9, Name = "Планшет PRESTIGIO Wize 4137 4G 1/16GB Black (PMT4137_4G_D_EU)", Price = 2_499, ProducerId = 8, CategoryId = 1, SubCategoryId = 2},
                new Product { Id = 10, Name = "Планшет APPLE iPad Pro Wi-Fi 1TB Space Gray (MHQY3RK/A)", Price = 63_999, ProducerId = 5, CategoryId = 1, SubCategoryId = 2},
                new Product { Id = 11, Name = "Сумка для ноутбука TUCANO Dritta Slim Blue (BDR15-B)", Price = 1_299, ProducerId = 9, CategoryId = 1, SubCategoryId = 3},
                new Product { Id = 12, Name = "Сумка для ноутбука TUCANO Dritta Slim Black (BDR15)", Price = 1_299, ProducerId = 9, CategoryId = 1, SubCategoryId = 3},
                new Product { Id = 13, Name = "Сумка для ноутбука CONTINENT CC-892", Price = 782, ProducerId = 10, CategoryId = 1, SubCategoryId = 3},
                new Product { Id = 14, Name = "Сумка для ноутбука PORTO PN16GP", Price = 353, ProducerId = 11, CategoryId = 1, SubCategoryId = 3},
                new Product { Id = 15, Name = "Сумка для ноутбука CASE LOGIC Laptop and Tablet Case (3201433)", Price = 1_299, ProducerId = 12, CategoryId = 1, SubCategoryId = 3},
                new Product { Id = 16, Name = "Процесор AMD Ryzen 7 3700X 3.6GHz AM4 (100-100000071BOX)", Price = 9_399, ProducerId = 13, CategoryId = 2, SubCategoryId = 4},
                new Product { Id = 17, Name = "Процесор INTEL Core i5-10600K 4.1GHz s1200 (BX8070110600K)", Price = 7_469, ProducerId = 14, CategoryId = 2, SubCategoryId = 4},
                new Product { Id = 18, Name = "Процесор AMD Ryzen 9 5950X 3.4GHz AM4 (100-100000059WOF)", Price = 25_389, ProducerId = 13, CategoryId = 2, SubCategoryId = 4},
                new Product { Id = 19, Name = "Процесор AMD Ryzen 7 5700G 3.8GHz AM4 (100-100000263BOX)", Price = 12_169, ProducerId = 13, CategoryId = 2, SubCategoryId = 4},
                new Product { Id = 20, Name = "Процесор INTEL Core i5-9600KF 3.7GHz s1151 (BX80684I59600KF)", Price = 6_133, ProducerId = 14, CategoryId = 2, SubCategoryId = 4},
                new Product { Id = 21, Name = "Материнська плата ASUS Prime B360M-K", Price = 1_818, ProducerId = 15, CategoryId = 2, SubCategoryId = 5},
                new Product { Id = 22, Name = "Материнська плата GIGABYTE B450M DS3H", Price = 1_911, ProducerId = 16, CategoryId = 2, SubCategoryId = 5},
                new Product { Id = 23, Name = "Материнська плата ASUS TUF Gaming X570-Plus", Price = 5_759, ProducerId = 15, CategoryId = 2, SubCategoryId = 5},
                new Product { Id = 24, Name = "Материнська плата AORUS X570 Master", Price = 11_375, ProducerId = 17, CategoryId = 2, SubCategoryId = 5},
                new Product { Id = 25, Name = "Материнська плата ASUS Prime H410M-A", Price = 2_309, ProducerId = 15, CategoryId = 2, SubCategoryId = 5},
                new Product { Id = 26, Name = "Відеокарта PALIT GeForce RTX 3080 GamingPro V1 LHR (NED3080019IA-132AA)", Price = 65_489, ProducerId = 18, CategoryId = 2, SubCategoryId = 6},
                new Product { Id = 27, Name = "Відеокарта MSI GeForce RTX 3060 Ti Gaming Z Trio 8G LHR", Price = 35_999, ProducerId = 19, CategoryId = 2, SubCategoryId = 6},
                new Product { Id = 28, Name = "Відеокарта GIGABYTE GeForce RTX 3060 Ti Gaming OC 8G Rev2.0 LHR (GV-N306TGAMING OC-8GD REV.2.0)", Price = 34_599, ProducerId = 16, CategoryId = 2, SubCategoryId = 6},
                new Product { Id = 29, Name = "Відеокарта AORUS GeForce RTX 3080 Xtreme 10G Rev2.0 LHR (GV-N3080AORUS X-10GD REV.2.0)", Price = 65_571, ProducerId = 17, CategoryId = 2, SubCategoryId = 6},
                new Product { Id = 30, Name = "Відеокарта ASUS Dual GeForce RTX 3060 Ti V2 OC Edition LHR (DUAL-RTX3060TI-O8G-V2)", Price = 34_869, ProducerId = 15, CategoryId = 2, SubCategoryId = 6},
                new Product { Id = 31, Name = "Модуль пам'яті HYPERX Predator DDR4 3000MHz 16GB Kit 2x8GB (HX430C15PB3K2/16)", Price = 2_849, ProducerId = 20, CategoryId = 2, SubCategoryId = 7},
                new Product { Id = 32, Name = "Модуль пам'яті KINGSTON KVR ValueRAM DDR4 2666MHz 16GB (KVR26N19D8/16)", Price = 2_159, ProducerId = 21, CategoryId = 2, SubCategoryId = 7},
                new Product { Id = 33, Name = "Модуль пам'яті HYPERX Predator DDR4 3000MHz 16GB (HX430C15PB3/16)", Price = 2_763, ProducerId = 20, CategoryId = 2, SubCategoryId = 7},
                new Product { Id = 34, Name = "Модуль пам'яті HYPERX Predator DDR4 3200MHz 16GB (HX432C16PB3/16)", Price = 2_651, ProducerId = 20, CategoryId = 2, SubCategoryId = 7},
                new Product { Id = 35, Name = "Модуль пам'яті HYPERX Predator RGB DDR4 3200MHz 32GB Kit 2x16GB (HX432C16PB3AK2/32)", Price = 5_389, ProducerId = 20, CategoryId = 2, SubCategoryId = 7},
                new Product { Id = 36, Name = "Монітор SAMSUNG S24F350FHI (LS24F350FHIXCI)", Price = 3_999, ProducerId = 7, CategoryId = 3, SubCategoryId = 8},
                new Product { Id = 37, Name = "Монітор PHILIPS 243V7QDAB/00", Price = 4_429, ProducerId = 22, CategoryId = 3, SubCategoryId = 8},
                new Product { Id = 38, Name = "Монітор DELL P2419H (210-APWU)", Price = 6_499, ProducerId = 4, CategoryId = 3, SubCategoryId = 8},
                new Product { Id = 39, Name = "Монітор ASUS ProArt PA27AC", Price = 21_599, ProducerId = 15, CategoryId = 3, SubCategoryId = 8},
                new Product { Id = 40, Name = "Монітор ASUS VP249QGR", Price = 6_599, ProducerId = 15, CategoryId = 3, SubCategoryId = 8},
                new Product { Id = 41, Name = "Клавіатура A4TECH KV-300H", Price = 799, ProducerId = 23, CategoryId = 3, SubCategoryId = 9},
                new Product { Id = 42, Name = "Клавіатура LOGITECH K120 UA OEM (920-002643)", Price = 299, ProducerId = 24, CategoryId = 3, SubCategoryId = 9},
                new Product { Id = 43, Name = "Комплект LOGITECH MK120 Desktop (920-002561)", Price = 499, ProducerId = 24, CategoryId = 3, SubCategoryId = 9},
                new Product { Id = 44, Name = "Комплект бездротовий LOGITECH MK270 Wireless Combo (920-004518)", Price = 999, ProducerId = 24, CategoryId = 3, SubCategoryId = 9},
                new Product { Id = 45, Name = "Клавіатура LOGITECH K280e (920-005215)", Price = 669, ProducerId = 24, CategoryId = 3, SubCategoryId = 9},
                new Product { Id = 46, Name = "Трекбол LOGITECH Wireless M570 (910-002090/910-001882)", Price = 2_599, ProducerId = 24, CategoryId = 3, SubCategoryId = 10},
                new Product { Id = 47, Name = "Миша LOGITECH M90 (910-001794)", Price = 199, ProducerId = 24, CategoryId = 3, SubCategoryId = 10},
                new Product { Id = 48, Name = "Миша LOGITECH M185 Swifty Gray (910-002238)", Price = 539, ProducerId = 24, CategoryId = 3, SubCategoryId = 10},
                new Product { Id = 49, Name = "Миша LOGITECH B100 Black (910-003357)", Price = 199, ProducerId = 24, CategoryId = 3, SubCategoryId = 10},
                new Product { Id = 50, Name = "Миша LOGITECH M100 (910-005003)", Price = 269, ProducerId = 24, CategoryId = 3, SubCategoryId = 10},
                new Product { Id = 51, Name = "Смартфон APPLE iPhone 12 Pro Max 512GB Graphite (MGDG3FS/A)", Price = 51_499, ProducerId = 5, CategoryId = 4, SubCategoryId = 11},
                new Product { Id = 52, Name = "Смартфон APPLE iPhone 12 Pro Max 256GB Pacific Blue (MGDF3FS/A)", Price = 43_499, ProducerId = 5, CategoryId = 4, SubCategoryId = 11},
                new Product { Id = 53, Name = "Смартфон XIAOMI Mi 11 Lite 6/128GB Boba Black", Price = 9_293, ProducerId = 25, CategoryId = 4, SubCategoryId = 11},
                new Product { Id = 54, Name = "Смартфон XIAOMI Redmi Note 10 Pro 6/128GB Onyx Gray", Price = 8_449, ProducerId = 25, CategoryId = 4, SubCategoryId = 11},
                new Product { Id = 55, Name = "Смартфон ZTE Blade A51 2/64GB Pearl Gray", Price = 3_199, ProducerId = 26, CategoryId = 4, SubCategoryId = 11},
                new Product { Id = 56, Name = "Мобільний телефон NOKIA 105 (2019) SS Black (16KIGB01A13)", Price = 549, ProducerId = 27, CategoryId = 4, SubCategoryId = 12},
                new Product { Id = 57, Name = "Мобільний телефон NOKIA 230 Dark Silver (A00026971)", Price = 1_999, ProducerId = 27, CategoryId = 4, SubCategoryId = 12},
                new Product { Id = 58, Name = "Мобільний телефон NOKIA 230 Light Silver (A00026972)", Price = 1_999, ProducerId = 27, CategoryId = 4, SubCategoryId = 12},
                new Product { Id = 59, Name = "Мобільний телефон NOKIA 230 Blue (16PCML01A02)", Price = 1_999, ProducerId = 27, CategoryId = 4, SubCategoryId = 12},
                new Product { Id = 60, Name = "Мобільний телефон NOKIA 106 (2018) (16NEBD01A02)", Price = 599, ProducerId = 27, CategoryId = 4, SubCategoryId = 12},
                new Product { Id = 61, Name = "Кабель-подовжувач ATCOM USB2.0 AM/AF Black 1.5м (17206)", Price = 39, ProducerId = 28, CategoryId = 4, SubCategoryId = 13},
                new Product { Id = 62, Name = "Кабель-подовжувач ATCOM USB3.0 AM/AF 0.8м (11202)", Price = 79, ProducerId = 28, CategoryId = 4, SubCategoryId = 13},
                new Product { Id = 63, Name = "Кабель BASEUS Cafule USB for Lightning Gray/Black 1м (CALKLF-BG1)", Price = 79, ProducerId = 29, CategoryId = 4, SubCategoryId = 13},
                new Product { Id = 64, Name = "Кабель BASEUS MVP 3-in-1 Mobile Game Black 1.2м (CAMLT-WZ01)", Price = 149, ProducerId = 29, CategoryId = 4, SubCategoryId = 13},
                new Product { Id = 65, Name = "Кабель BASEUS Cafule USB for Type-C Gray/Black 1м (CATKLF-BG1)", Price = 127, ProducerId = 29, CategoryId = 4, SubCategoryId = 13}
            });

            builder.Entity<ProductPhoto>().HasData(new ProductPhoto[]
            {
                 new ProductPhoto { Id = 1, Path = "https://i.can.ua/images/650x650/goods/7475/7475025.jpg", ProductId = 1 },
                 new ProductPhoto { Id = 2, Path = "https://i.can.ua/images/650x650/goods/7475/7475035.jpg", ProductId = 1 },
                 new ProductPhoto { Id = 3, Path = "https://i.can.ua/images/650x650/goods/7475/7475045.jpg", ProductId = 1 },
                 new ProductPhoto { Id = 4, Path = "https://i.can.ua/images/650x650/goods/7516/7516291.jpg", ProductId = 2 },
                 new ProductPhoto { Id = 5, Path = "https://i.can.ua/images/650x650/goods/7516/7516301.jpg", ProductId = 2 },
                 new ProductPhoto { Id = 6, Path = "https://i.can.ua/images/650x650/goods/7516/7516311.jpg", ProductId = 2 },
                 new ProductPhoto { Id = 7, Path = "https://i.can.ua/images/650x650/goods/7794/7794334.jpg", ProductId = 3 },
                 new ProductPhoto { Id = 8, Path = "https://i.can.ua/images/650x650/goods/7794/7794344.jpg", ProductId = 3 },
                 new ProductPhoto { Id = 9, Path = "https://i.can.ua/images/650x650/goods/7794/7794354.jpg", ProductId = 3 },
                 new ProductPhoto { Id = 10, Path = "https://i.can.ua/images/650x650/goods/8921/8921000.jpg", ProductId = 4 },
                 new ProductPhoto { Id = 11, Path = "https://i.can.ua/images/650x650/goods/8921/8921010.jpg", ProductId = 4 },
                 new ProductPhoto { Id = 12, Path = "https://i.can.ua/images/650x650/goods/8921/8921020.jpg", ProductId = 4 },
                 new ProductPhoto { Id = 13, Path = "https://i.can.ua/images/650x650/goods/8921/8921430.jpg", ProductId = 5 },
                 new ProductPhoto { Id = 14, Path = "https://i.can.ua/images/700x700/goods/8921/8921450.jpg", ProductId = 5 },
                 new ProductPhoto { Id = 15, Path = "https://i.can.ua/images/700x700/goods/8921/8921460.jpg", ProductId = 5 },
                 new ProductPhoto { Id = 16, Path = "https://i.can.ua/images/650x650/goods/5403/5403911.jpg", ProductId = 6 },
                 new ProductPhoto { Id = 17, Path = "https://i.can.ua/images/650x650/goods/5403/5403921.jpg", ProductId = 6 },
                 new ProductPhoto { Id = 18, Path = "https://i.can.ua/images/650x650/goods/5403/5403931.jpg", ProductId = 6 },
                 new ProductPhoto { Id = 19, Path = "https://i.can.ua/images/650x650/goods/6841/6841261.jpg", ProductId = 7 },
                 new ProductPhoto { Id = 20, Path = "https://i.can.ua/images/700x700/goods/6841/6841271.jpg", ProductId = 7 },
                 new ProductPhoto { Id = 21, Path = "https://i.can.ua/images/700x700/goods/6841/6841291.jpg", ProductId = 7 },
                 new ProductPhoto { Id = 22, Path = "https://i.can.ua/images/650x650/goods/8949/8949090.jpg", ProductId = 8 },
                 new ProductPhoto { Id = 23, Path = "https://i.can.ua/images/650x650/goods/8949/8949120.jpg", ProductId = 8 },
                 new ProductPhoto { Id = 24, Path = "https://i.can.ua/images/650x650/goods/8949/8949130.jpg", ProductId = 8 },
                 new ProductPhoto { Id = 25, Path = "https://i.can.ua/images/650x650/goods/9019/9019872.jpg", ProductId = 9 },
                 new ProductPhoto { Id = 26, Path = "https://i.can.ua/images/650x650/goods/9019/9019882.jpg", ProductId = 9 },
                 new ProductPhoto { Id = 27, Path = "https://i.can.ua/images/650x650/goods/9019/9019912.jpg", ProductId = 9 },
                 new ProductPhoto { Id = 28, Path = "https://i.can.ua/images/650x650/goods/9073/9073482.jpg", ProductId = 10 },
                 new ProductPhoto { Id = 29, Path = "https://i.can.ua/images/650x650/goods/9073/9073502.jpg", ProductId = 10 },
                 new ProductPhoto { Id = 30, Path = "https://i.can.ua/images/650x650/goods/9073/9073522.jpg", ProductId = 10 },
                 new ProductPhoto { Id = 31, Path = "https://i.can.ua/goods/234/234516.jpg", ProductId = 11 },
                 new ProductPhoto { Id = 32, Path = "https://i.can.ua/goods/8489/8489478.jpg", ProductId = 11 },
                 new ProductPhoto { Id = 33, Path = "https://i.can.ua/images/700x700/goods/8489/8489488.jpg", ProductId = 11 },
                 new ProductPhoto { Id = 34, Path = "https://i.can.ua/goods/92/92454.jpg", ProductId = 12 },
                 new ProductPhoto { Id = 35, Path = "https://i.can.ua/images/650x650/goods/8489/8489418.jpg", ProductId = 12 },
                 new ProductPhoto { Id = 36, Path = "https://i.can.ua/images/650x650/goods/8489/8489428.jpg", ProductId = 12 },
                 new ProductPhoto { Id = 37, Path = "https://i.can.ua/images/650x650/goods/2647/2647511.jpg", ProductId = 13 },
                 new ProductPhoto { Id = 38, Path = "https://i.can.ua/images/650x650/goods/2647/2647531.jpg", ProductId = 13 },
                 new ProductPhoto { Id = 39, Path = "https://i.can.ua/images/650x650/goods/2647/2647541.jpg", ProductId = 13 },
                 new ProductPhoto { Id = 40, Path = "https://i.can.ua/images/650x650/goods/689/689944.jpg", ProductId = 14 },
                 new ProductPhoto { Id = 41, Path = "https://i.can.ua/goods/689/689954.jpg", ProductId = 14 },
                 new ProductPhoto { Id = 42, Path = "https://i.can.ua/images/650x650/goods/1381/1381399.jpg", ProductId = 15 },
                 new ProductPhoto { Id = 43, Path = "https://i.can.ua/images/650x650/goods/1381/1381419.jpg", ProductId = 15 },
                 new ProductPhoto { Id = 44, Path = "https://i.can.ua/images/650x650/goods/1381/1381429.jpg", ProductId = 15 },
                 new ProductPhoto { Id = 45, Path = "https://i.can.ua/images/650x650/goods/5507/5507930.jpg", ProductId = 16 },
                 new ProductPhoto { Id = 46, Path = "https://i.can.ua/images/700x700/goods/5507/5507950.jpg", ProductId = 16 },
                 new ProductPhoto { Id = 47, Path = "https://i.can.ua/images/700x700/goods/5507/5507960.jpg", ProductId = 16 },
                 new ProductPhoto { Id = 48, Path = "https://i.can.ua/images/650x650/goods/6815/6815741.jpg", ProductId = 17 },
                 new ProductPhoto { Id = 49, Path = "https://i.can.ua/goods/7404/7404113.jpg", ProductId = 18 },
                 new ProductPhoto { Id = 50, Path = "https://i.can.ua/goods/8882/8882700.jpg", ProductId = 19 },
                 new ProductPhoto { Id = 51, Path = "https://i.can.ua/images/650x650/goods/5297/5297195.jpg", ProductId = 20 },
                 new ProductPhoto { Id = 52, Path = "https://i.can.ua/images/650x650/goods/3904/3904141.jpg", ProductId = 21 },
                 new ProductPhoto { Id = 53, Path = "https://i.can.ua/images/650x650/goods/3904/3904157.jpg", ProductId = 21 },
                 new ProductPhoto { Id = 54, Path = "https://i.can.ua/images/650x650/goods/3904/3904177.jpg", ProductId = 21 },
                 new ProductPhoto { Id = 55, Path = "https://i.can.ua/images/650x650/goods/4253/4253827.jpg", ProductId = 22 },
                 new ProductPhoto { Id = 56, Path = "https://i.can.ua/goods/4253/4253837.jpg", ProductId = 22 },
                 new ProductPhoto { Id = 57, Path = "https://i.can.ua/goods/4253/4253867.jpg", ProductId = 22 },
                 new ProductPhoto { Id = 58, Path = "https://i.can.ua/images/650x650/goods/5494/5494099.jpg", ProductId = 23 },
                 new ProductPhoto { Id = 59, Path = "https://i.can.ua/images/700x700/goods/5494/5494109.jpg", ProductId = 23 },
                 new ProductPhoto { Id = 60, Path = "https://i.can.ua/images/700x700/goods/6899/6899685.jpg", ProductId = 23 },
                 new ProductPhoto { Id = 61, Path = "https://i.can.ua/images/700x700/goods/5598/5598366.jpg", ProductId = 24 },
                 new ProductPhoto { Id = 62, Path = "https://i.can.ua/images/700x700/goods/5598/5598376.jpg", ProductId = 24 },
                 new ProductPhoto { Id = 63, Path = "https://i.can.ua/images/700x700/goods/5598/5598396.jpg", ProductId = 24 },
                 new ProductPhoto { Id = 64, Path = "https://i.can.ua/goods/6908/6908615.jpg", ProductId = 25 },
                 new ProductPhoto { Id = 65, Path = "https://i.can.ua/images/700x700/goods/6908/6908625.jpg", ProductId = 25 },
                 new ProductPhoto { Id = 66, Path = "https://i.can.ua/images/700x700/goods/6908/6908645.jpg", ProductId = 25 },
                 new ProductPhoto { Id = 67, Path = "https://i.can.ua/images/650x650/goods/7241/7241957.jpg", ProductId = 26 },
                 new ProductPhoto { Id = 68, Path = "https://i.can.ua/images/700x700/goods/7241/7241967.jpg", ProductId = 26 },
                 new ProductPhoto { Id = 69, Path = "https://i.can.ua/images/700x700/goods/7242/7242007.jpg", ProductId = 26 },
                 new ProductPhoto { Id = 70, Path = "https://i.can.ua/images/650x650/goods/8631/8631450.jpg", ProductId = 27 },
                 new ProductPhoto { Id = 71, Path = "https://i.can.ua/images/650x650/goods/8631/8631460.jpg", ProductId = 27 },
                 new ProductPhoto { Id = 72, Path = "https://i.can.ua/images/650x650/goods/8631/8631490.jpg", ProductId = 27 },
                 new ProductPhoto { Id = 73, Path = "https://i.can.ua/images/650x650/goods/8812/8812114.jpg", ProductId = 28 },
                 new ProductPhoto { Id = 74, Path = "https://i.can.ua/images/700x700/goods/8812/8812124.jpg", ProductId = 28 },
                 new ProductPhoto { Id = 75, Path = "https://i.can.ua/images/700x700/goods/8812/8812174.jpg", ProductId = 28 },
                 new ProductPhoto { Id = 76, Path = "https://i.can.ua/images/650x650/goods/8821/8821054.jpg", ProductId = 29 },
                 new ProductPhoto { Id = 77, Path = "https://i.can.ua/images/650x650/goods/8821/8821064.jpg", ProductId = 29 },
                 new ProductPhoto { Id = 78, Path = "https://i.can.ua/images/650x650/goods/8821/8821094.jpg", ProductId = 29 },
                 new ProductPhoto { Id = 79, Path = "https://i.can.ua/images/650x650/goods/8821/8821144.jpg", ProductId = 30 },
                 new ProductPhoto { Id = 80, Path = "https://i.can.ua/images/700x700/goods/8821/8821154.jpg", ProductId = 30 },
                 new ProductPhoto { Id = 81, Path = "https://i.can.ua/images/700x700/goods/8821/8821184.jpg", ProductId = 30 },
                 new ProductPhoto { Id = 82, Path = "https://i.can.ua/images/650x650/goods/1094/1094139.jpg", ProductId = 31 },
                 new ProductPhoto { Id = 83, Path = "https://i.can.ua/images/650x650/goods/3760/3760893.jpg", ProductId = 32 },
                 new ProductPhoto { Id = 84, Path = "https://i.can.ua/images/650x650/goods/2205/2205731.jpg", ProductId = 33 },
                 new ProductPhoto { Id = 85, Path = "https://i.can.ua/images/650x650/goods/4759/4759161.jpg", ProductId = 34 },
                 new ProductPhoto { Id = 86, Path = "https://i.can.ua/images/650x650/goods/6235/6235151.jpg", ProductId = 35 },
                 new ProductPhoto { Id = 87, Path = "https://i.can.ua/images/700x700/goods/6235/6235161.jpg", ProductId = 35 },
                 new ProductPhoto { Id = 88, Path = "https://i.can.ua/images/700x700/goods/6235/6235181.jpg", ProductId = 35 },
                 new ProductPhoto { Id = 89, Path = "https://i.can.ua/images/650x650/goods/1010/1010507.jpg", ProductId = 36 },
                 new ProductPhoto { Id = 90, Path = "https://i.can.ua/goods/1010/1010527.jpg", ProductId = 36 },
                 new ProductPhoto { Id = 91, Path = "https://i.can.ua/images/650x650/goods/1010/1010537.jpg", ProductId = 36 },
                 new ProductPhoto { Id = 92, Path = "https://i.can.ua/images/650x650/goods/2208/2208731.jpg", ProductId = 37 },
                 new ProductPhoto { Id = 93, Path = "https://i.can.ua/images/700x700/goods/2208/2208751.jpg", ProductId = 37 },
                 new ProductPhoto { Id = 94, Path = "https://i.can.ua/images/700x700/goods/8629/8629570.jpg", ProductId = 37 },
                 new ProductPhoto { Id = 95, Path = "https://i.can.ua/images/650x650/goods/4297/4297677.jpg", ProductId = 38 },
                 new ProductPhoto { Id = 96, Path = "https://i.can.ua/goods/4297/4297707.jpg", ProductId = 38 },
                 new ProductPhoto { Id = 97, Path = "https://i.can.ua/goods/4297/4297717.jpg", ProductId = 38 },
                 new ProductPhoto { Id = 98, Path = "https://i.can.ua/images/650x650/goods/3880/3880357.jpg", ProductId = 39 },
                 new ProductPhoto { Id = 99, Path = "https://i.can.ua/goods/3880/3880387.jpg", ProductId = 39 },
                 new ProductPhoto { Id = 100, Path = "https://i.can.ua/goods/3880/3880397.jpg", ProductId = 39 },
                 new ProductPhoto { Id = 101, Path = "https://i.can.ua/images/650x650/goods/7388/7388233.jpg", ProductId = 40 },
                 new ProductPhoto { Id = 102, Path = "https://i.can.ua/images/700x700/goods/8629/8629530.jpg", ProductId = 40 },
                 new ProductPhoto { Id = 103, Path = "https://i.can.ua/images/700x700/goods/8629/8629540.jpg", ProductId = 40 },
                 new ProductPhoto { Id = 104, Path = "https://i.can.ua/images/650x650/goods/196/196536.jpg", ProductId = 41 },
                 new ProductPhoto { Id = 105, Path = "https://i.can.ua/images/700x700/goods/8225/8225656.jpg", ProductId = 41 },
                 new ProductPhoto { Id = 106, Path = "https://i.can.ua/images/700x700/goods/8629/8629350.jpg", ProductId = 41 },
                 new ProductPhoto { Id = 107, Path = "https://i.can.ua/images/650x650/goods/225/225216.jpg", ProductId = 42 },
                 new ProductPhoto { Id = 108, Path = "https://i.can.ua/images/700x700/goods/8629/8629430.jpg", ProductId = 42 },
                 new ProductPhoto { Id = 109, Path = "https://i.can.ua/images/700x700/goods/8629/8629440.jpg", ProductId = 42 },
                 new ProductPhoto { Id = 110, Path = "https://i.can.ua/images/650x650/goods/8225/8225736.jpg", ProductId = 43 },
                 new ProductPhoto { Id = 111, Path = "https://i.can.ua/images/700x700/goods/8539/8539550.jpg", ProductId = 43 },
                 new ProductPhoto { Id = 112, Path = "https://i.can.ua/goods/8539/8539560.jpg", ProductId = 43 },
                 new ProductPhoto { Id = 113, Path = "https://i.can.ua/images/650x650/goods/194/194876.jpg", ProductId = 44 },
                 new ProductPhoto { Id = 114, Path = "https://i.can.ua/images/700x700/goods/8225/8225786.jpg", ProductId = 44 },
                 new ProductPhoto { Id = 115, Path = "https://i.can.ua/goods/1190/1190999.jpg", ProductId = 45 },
                 new ProductPhoto { Id = 116, Path = "https://i.can.ua/goods/1191/1191019.jpg", ProductId = 45 },
                 new ProductPhoto { Id = 117, Path = "https://i.can.ua/goods/1191/1191029.jpg", ProductId = 45 },
                 new ProductPhoto { Id = 118, Path = "https://i.can.ua/images/650x650/goods/113/113858.jpg", ProductId = 46 },
                 new ProductPhoto { Id = 119, Path = "https://i.can.ua/images/650x650/goods/8725/8725630.jpg", ProductId = 46 },
                 new ProductPhoto { Id = 120, Path = "https://i.can.ua/images/650x650/goods/8725/8725640.jpg", ProductId = 46 },
                 new ProductPhoto { Id = 121, Path = "https://i.can.ua/images/650x650/goods/254/254966.jpg", ProductId = 47 },
                 new ProductPhoto { Id = 122, Path = "https://i.can.ua/goods/4262/4262467.jpg", ProductId = 47 },
                 new ProductPhoto { Id = 123, Path = "https://i.can.ua/images/650x650/goods/231/231196.jpg", ProductId = 48 },
                 new ProductPhoto { Id = 124, Path = "https://i.can.ua/images/650x650/goods/4262/4262507.jpg", ProductId = 48 },
                 new ProductPhoto { Id = 125, Path = "https://i.can.ua/images/650x650/goods/8642/8642380.jpg", ProductId = 48 },
                 new ProductPhoto { Id = 126, Path = "https://i.can.ua/images/650x650/goods/282/282970.jpg", ProductId = 49 },
                 new ProductPhoto { Id = 127, Path = "https://i.can.ua/images/650x650/goods/4263/4263647.jpg", ProductId = 49 },
                 new ProductPhoto { Id = 128, Path = "https://i.can.ua/images/650x650/goods/8642/8642270.jpg", ProductId = 49 },
                 new ProductPhoto { Id = 129, Path = "https://i.can.ua/images/650x650/goods/2024/2024039.jpg", ProductId = 50 },
                 new ProductPhoto { Id = 130, Path = "https://i.can.ua/images/650x650/goods/2024/2024049.jpg", ProductId = 50 },
                 new ProductPhoto { Id = 131, Path = "https://i.can.ua/images/650x650/goods/2024/2024059.jpg", ProductId = 50 },
                 new ProductPhoto { Id = 132, Path = "https://i.can.ua/images/650x650/goods/7593/7593502.jpg", ProductId = 51 },
                 new ProductPhoto { Id = 133, Path = "https://i.can.ua/images/700x700/goods/7593/7593512.jpg", ProductId = 51 },
                 new ProductPhoto { Id = 134, Path = "https://i.can.ua/images/700x700/goods/7593/7593522.jpg", ProductId = 51 },
                 new ProductPhoto { Id = 135, Path = "https://i.can.ua/images/700x700/goods/7666/7666872.jpg", ProductId = 52 },
                 new ProductPhoto { Id = 136, Path = "https://i.can.ua/images/700x700/goods/7666/7666882.jpg", ProductId = 52 },
                 new ProductPhoto { Id = 137, Path = "https://i.can.ua/images/700x700/goods/7666/7666902.jpg", ProductId = 52 },
                 new ProductPhoto { Id = 138, Path = "https://i.can.ua/images/650x650/goods/8167/8167720.jpg", ProductId = 53 },
                 new ProductPhoto { Id = 139, Path = "https://i.can.ua/images/700x700/goods/8167/8167740.jpg", ProductId = 53 },
                 new ProductPhoto { Id = 140, Path = "https://i.can.ua/images/700x700/goods/8167/8167760.jpg", ProductId = 53 },
                 new ProductPhoto { Id = 141, Path = "https://i.can.ua/images/650x650/goods/8393/8393686.jpg", ProductId = 54 },
                 new ProductPhoto { Id = 142, Path = "https://i.can.ua/images/700x700/goods/8393/8393736.jpg", ProductId = 54 },
                 new ProductPhoto { Id = 143, Path = "https://i.can.ua/images/700x700/goods/8393/8393726.jpg", ProductId = 54 },
                 new ProductPhoto { Id = 144, Path = "https://i.can.ua/images/700x700/goods/8936/8936210.jpg", ProductId = 55 },
                 new ProductPhoto { Id = 145, Path = "https://i.can.ua/images/700x700/goods/8936/8936230.jpg", ProductId = 55 },
                 new ProductPhoto { Id = 146, Path = "https://i.can.ua/images/700x700/goods/8936/8936250.jpg", ProductId = 55 },
                 new ProductPhoto { Id = 147, Path = "https://i.can.ua/images/650x650/goods/5905/5905459.jpg", ProductId = 56 },
                 new ProductPhoto { Id = 148, Path = "https://i.can.ua/images/650x650/goods/5905/5905469.jpg", ProductId = 56 },
                 new ProductPhoto { Id = 149, Path = "https://i.can.ua/images/650x650/goods/2203/2203491.jpg", ProductId = 57 },
                 new ProductPhoto { Id = 150, Path = "https://i.can.ua/images/650x650/goods/2203/2203501.jpg", ProductId = 57 },
                 new ProductPhoto { Id = 151, Path = "https://i.can.ua/images/650x650/goods/2203/2203511.jpg", ProductId = 58 },
                 new ProductPhoto { Id = 152, Path = "https://i.can.ua/images/650x650/goods/2203/2203521.jpg", ProductId = 58 },
                 new ProductPhoto { Id = 153, Path = "https://i.can.ua/goods/4925/4925511.jpg", ProductId = 59 },
                 new ProductPhoto { Id = 154, Path = "https://i.can.ua/goods/4925/4925521.jpg", ProductId = 59 },
                 new ProductPhoto { Id = 155, Path = "https://i.can.ua/images/650x650/goods/4971/4971631.jpg", ProductId = 60 },
                 new ProductPhoto { Id = 156, Path = "https://i.can.ua/images/650x650/goods/4971/4971641.jpg", ProductId = 60 },
                 new ProductPhoto { Id = 157, Path = "https://i.can.ua/images/650x650/goods/1691/1691427.jpg", ProductId = 61 },
                 new ProductPhoto { Id = 158, Path = "https://i.can.ua/goods/1691/1691600.jpg", ProductId = 62 },
                 new ProductPhoto { Id = 159, Path = "https://i.can.ua/images/650x650/goods/4909/4909855.jpg", ProductId = 63 },
                 new ProductPhoto { Id = 160, Path = "https://i.can.ua/images/650x650/goods/6702/6702343.jpg", ProductId = 64 },
                 new ProductPhoto { Id = 161, Path = "https://i.can.ua/images/650x650/goods/4919/4919571.jpg", ProductId = 65 }
            });

            builder.Entity<Characteristic>().HasData(new Characteristic[]
            {
                new Characteristic { Id = 1, Name = "Процесор", Value = "Intel Core i7-1165G7", ProductId = 1 },
                new Characteristic { Id = 2, Name = "Кількість ядер процесора", Value = "4", ProductId = 1 },
                new Characteristic { Id = 3, Name = "Частота процесора", Value = "2.8 - 4.7 ГГц", ProductId = 1 },
                new Characteristic { Id = 4, Name = "Діагональ екрану", Value = "14", ProductId = 1 },
                new Characteristic { Id = 5, Name = "Оперативна пам'ять", Value = "16 ГБ", ProductId = 1 },
                new Characteristic { Id = 6, Name = "Ємність SSD:", Value = "1 ТБ", ProductId = 1 },
                new Characteristic { Id = 7, Name = "Процесор", Value = "AMD Ryzen 5 3500U", ProductId = 2 },
                new Characteristic { Id = 8, Name = "Кількість ядер процесора", Value = "4", ProductId = 2 },
                new Characteristic { Id = 9, Name = "Частота процесора", Value = "2.1 - 3.7 ГГц", ProductId = 2 },
                new Characteristic { Id = 10, Name = "Діагональ екрану", Value = "14", ProductId = 2 },
                new Characteristic { Id = 11, Name = "Оперативна пам'ять", Value = "8 ГБ", ProductId = 2 },
                new Characteristic { Id = 12, Name = "Ємність SSD", Value = "256 ГБ", ProductId = 2 },
                new Characteristic { Id = 13, Name = "Процесор", Value = "Intel Core i5-L16G7", ProductId = 3 },
                new Characteristic { Id = 14, Name = "Кількість ядер процесора", Value = "5", ProductId = 3 },
                new Characteristic { Id = 15, Name = "Частота процесора", Value = "1.4 - 3 ГГц", ProductId = 3 },
                new Characteristic { Id = 16, Name = "Діагональ екрану", Value = "13.3", ProductId = 3 },
                new Characteristic { Id = 17, Name = "Оперативна пам'ять", Value = "8 ГБ", ProductId = 3 },
                new Characteristic { Id = 18, Name = "Ємність SSD", Value = "512 ГБ", ProductId = 3 },
                new Characteristic { Id = 19, Name = "Процесор", Value = "Intel Core i5-10300H", ProductId = 4 },
                new Characteristic { Id = 20, Name = "Кількість ядер процесора", Value = "4", ProductId = 4 },
                new Characteristic { Id = 21, Name = "Частота процесора", Value = "2.5 - 4.5 ГГц", ProductId = 4 },
                new Characteristic { Id = 22, Name = "Діагональ екрану", Value = "16.1", ProductId = 4 },
                new Characteristic { Id = 23, Name = "Оперативна пам'ять", Value = "16 ГБ", ProductId = 4 },
                new Characteristic { Id = 24, Name = "Ємність SSD", Value = "256 ГБ", ProductId = 4 },
                new Characteristic { Id = 25, Name = "Процесор", Value = "Intel Core i5-1145G7", ProductId = 5 },
                new Characteristic { Id = 26, Name = "Кількість ядер процесора", Value = "4", ProductId = 5 },
                new Characteristic { Id = 27, Name = "Частота процесора", Value = "2.6 - 4.4 ГГц", ProductId = 5 },
                new Characteristic { Id = 28, Name = "Діагональ екрану", Value = "14", ProductId = 5 },
                new Characteristic { Id = 29, Name = "Оперативна пам'ять", Value = "16 ГБ", ProductId = 5 },
                new Characteristic { Id = 30, Name = "Ємність SSD", Value = "512 ГБ", ProductId = 5 },
                new Characteristic { Id = 31, Name = "Діагональ дисплея", Value = "10.5", ProductId = 6 },
                new Characteristic { Id = 32, Name = "Процесор", Value = "Apple A12 Bionic (6-ядерний 2.4 ГГц)", ProductId = 6 },
                new Characteristic { Id = 33, Name = "Роздільна здатність екрану", Value = "	2224 × 1668", ProductId = 6 },
                new Characteristic { Id = 34, Name = "Об'єм оперативної пам'яті", Value = "3 GB", ProductId = 6 },
                new Characteristic { Id = 35, Name = "Об'єм вбудованої пам'яті", Value = "	64 GB", ProductId = 6 },
                new Characteristic { Id = 36, Name = "Камера", Value = "8/7 Мп", ProductId = 6 },
                new Characteristic { Id = 37, Name = "Процесор", Value = "Intel Core i5-1035G4 (4-ядерний 1.1 ГГц)", ProductId = 7 },
                new Characteristic { Id = 38, Name = "Об'єм оперативної пам'яті", Value = "8 GB", ProductId = 7 },
                new Characteristic { Id = 39, Name = "Об'єм вбудованої пам'яті", Value = "256 GB", ProductId = 7 },
                new Characteristic { Id = 40, Name = "Камера", Value = "8/5 Мп", ProductId = 7 },
                new Characteristic { Id = 41, Name = "Роздільна здатність екрану", Value = "2736 × 1824", ProductId = 7 },
                new Characteristic { Id = 42, Name = "Діагональ дисплея", Value = "12.3", ProductId = 7 },
                new Characteristic { Id = 43, Name = "Діагональ дисплея", Value = "12.4", ProductId = 8 },
                new Characteristic { Id = 44, Name = "Роздільна здатність екрану", Value = "2560 × 1600", ProductId = 8 },
                new Characteristic { Id = 45, Name = "Процесор", Value = "Qualcomm Snapdragon 750G SM7225 (2x2.2 GHz Kryo 570 & 6x1.8 GHz Kryo 570)", ProductId = 8 },
                new Characteristic { Id = 46, Name = "Об'єм оперативної пам'яті", Value = "4 GB", ProductId = 8 },
                new Characteristic { Id = 47, Name = "Об'єм вбудованої пам'яті", Value = "64 GB", ProductId = 8 },
                new Characteristic { Id = 48, Name = "Камера", Value = "8/5 Мп", ProductId = 8 },
                new Characteristic { Id = 49, Name = "Операційна система", Value = "Android", ProductId = 9 },
                new Characteristic { Id = 50, Name = "Діагональ дисплея", Value = "7", ProductId = 9 },
                new Characteristic { Id = 51, Name = "Роздільна здатність екрану", Value = "1024 × 600", ProductId = 9 },
                new Characteristic { Id = 52, Name = "Процесор", Value = "Spreadtrum SC9832 (4 x 1.3 ггц ARM Cortex-A7)", ProductId = 9 },
                new Characteristic { Id = 53, Name = "Об'єм оперативної пам'яті", Value = "1 GB", ProductId = 9 },
                new Characteristic { Id = 54, Name = "Об'єм вбудованої пам'яті", Value = "16 GB", ProductId = 9 },
                new Characteristic { Id = 55, Name = "Камера", Value = "12/12 Мп", ProductId = 10 },
                new Characteristic { Id = 56, Name = "Діагональ дисплея", Value = "11", ProductId = 10 },
                new Characteristic { Id = 57, Name = "Роздільна здатність екрану", Value = "2388 × 1668", ProductId = 10 },
                new Characteristic { Id = 58, Name = "Процесор", Value = "Apple M1 (8-ядерний 3.2 ггц)", ProductId = 10 },
                new Characteristic { Id = 59, Name = "Об'єм оперативної пам'яті", Value = "16 GB", ProductId = 10 },
                new Characteristic { Id = 60, Name = "Об'єм вбудованої пам'яті", Value = "1 TB", ProductId = 10 },
                new Characteristic { Id = 61, Name = "Модель", Value = "Dritta Slim", ProductId = 11 },
                new Characteristic { Id = 62, Name = "Для ноутбуків з діагоналлю", Value = "15", ProductId = 11 },
                new Characteristic { Id = 63, Name = "Фіксуючі елементи", Value = "блискавка", ProductId = 11 },
                new Characteristic { Id = 64, Name = "Матеріал", Value = "полиэстер", ProductId = 11 },
                new Characteristic { Id = 65, Name = "Колір", Value = "синій", ProductId = 11 },
                new Characteristic { Id = 66, Name = "Модель", Value = "Dritta Slim", ProductId = 12 },
                new Characteristic { Id = 67, Name = "Для ноутбуків з діагоналлю", Value = "15", ProductId = 12 },
                new Characteristic { Id = 68, Name = "Фіксуючі елементи", Value = "блискавка", ProductId = 12 },
                new Characteristic { Id = 69, Name = "Матеріал", Value = "полиэстер", ProductId = 12 },
                new Characteristic { Id = 70, Name = "Колір", Value = "чорний", ProductId = 12 },
                new Characteristic { Id = 71, Name = "Модель", Value = "	CC-892", ProductId = 13 },
                new Characteristic { Id = 72, Name = "Для ноутбуків з діагоналлю", Value = "15.6", ProductId = 13 },
                new Characteristic { Id = 73, Name = "Фіксуючі елементи", Value = "блискавка", ProductId = 13 },
                new Characteristic { Id = 74, Name = "Матеріал", Value = "нейлон, полиэстер", ProductId = 13 },
                new Characteristic { Id = 75, Name = "Колір", Value = "чорний", ProductId = 13 },
                new Characteristic { Id = 76, Name = "Модель", Value = "PN16GP", ProductId = 14 },
                new Characteristic { Id = 77, Name = "Для ноутбуків з діагоналлю", Value = "15.6", ProductId = 14 },
                new Characteristic { Id = 78, Name = "Фіксуючі елементи", Value = "блискавка", ProductId = 14 },
                new Characteristic { Id = 79, Name = "Матеріал", Value = "нейлон, полиэстер", ProductId = 14 },
                new Characteristic { Id = 80, Name = "Колір", Value = "сірий", ProductId = 14 },
                new Characteristic { Id = 81, Name = "Модель", Value = "Laptop and Tablet Case", ProductId = 15 },
                new Characteristic { Id = 82, Name = "Для ноутбуків з діагоналлю", Value = "15.6", ProductId = 15 },
                new Characteristic { Id = 83, Name = "Фіксуючі елементи", Value = "блискавка", ProductId = 15 },
                new Characteristic { Id = 84, Name = "Матеріал", Value = "полиэстер", ProductId = 15 },
                new Characteristic { Id = 85, Name = "Колір", Value = "чорний", ProductId = 15 },
                new Characteristic { Id = 86, Name = "Модель", Value = "Ryzen 7 3700X", ProductId = 16 },
                new Characteristic { Id = 87, Name = "Кількість ядер", Value = "8", ProductId = 16 },
                new Characteristic { Id = 88, Name = "Кількість потоків", Value = "16", ProductId = 16 },
                new Characteristic { Id = 89, Name = "Частота процесора", Value = "3.6-4.4 ГГц", ProductId = 16 },
                new Characteristic { Id = 90, Name = "Об'єм кеш-пам'яті L3", Value = "32 МБ", ProductId = 16 },
                new Characteristic { Id = 91, Name = "Cтандарт пам'яті", Value = "DDR4 3200 мгц", ProductId = 16 },
                new Characteristic { Id = 92, Name = "Модель", Value = "Core i5-10600K", ProductId = 17 },
                new Characteristic { Id = 93, Name = "Кількість ядер", Value = "6", ProductId = 17 },
                new Characteristic { Id = 94, Name = "Кількість потоків", Value = "12", ProductId = 17 },
                new Characteristic { Id = 95, Name = "Частота процесора", Value = "4.1-4.8 ГГц", ProductId = 17 },
                new Characteristic { Id = 96, Name = "Об'єм кеш-пам'яті L3", Value = "12 МБ", ProductId = 17 },
                new Characteristic { Id = 97, Name = "Cтандарт пам'яті", Value = "DDR4 2666 мгц", ProductId = 17 },
                new Characteristic { Id = 98, Name = "Модель", Value = "Ryzen 9 5950X", ProductId = 18 },
                new Characteristic { Id = 99, Name = "Кількість ядер", Value = "16", ProductId = 18 },
                new Characteristic { Id = 100, Name = "Кількість потоків", Value = "32", ProductId = 18 },
                new Characteristic { Id = 101, Name = "Частота процесора", Value = "3.4-4.9 ГГц", ProductId = 18 },
                new Characteristic { Id = 102, Name = "Об'єм кеш-пам'яті L3", Value = "64 МБ", ProductId = 18 },
                new Characteristic { Id = 103, Name = "Cтандарт пам'яті", Value = "DDR4 3200 мгц", ProductId = 18 },
                new Characteristic { Id = 104, Name = "Модель", Value = "Ryzen 7 5700G", ProductId = 19 },
                new Characteristic { Id = 105, Name = "Кількість ядер", Value = "8", ProductId = 19 },
                new Characteristic { Id = 106, Name = "Кількість потоків", Value = "16", ProductId = 19 },
                new Characteristic { Id = 107, Name = "Частота процесора", Value = "3.8-4.6 ГГц", ProductId = 19 },
                new Characteristic { Id = 108, Name = "Об'єм кеш-пам'яті L3", Value = "16 МБ", ProductId = 19 },
                new Characteristic { Id = 109, Name = "Cтандарт пам'яті", Value = "DDR4 3200 мгц", ProductId = 19 },
                new Characteristic { Id = 110, Name = "Модель", Value = "Core i5-9600KF", ProductId = 20 },
                new Characteristic { Id = 111, Name = "Кількість ядер", Value = "6", ProductId = 20 },
                new Characteristic { Id = 112, Name = "Кількість потоків", Value = "6", ProductId = 20 },
                new Characteristic { Id = 113, Name = "Об'єм кеш-пам'яті L3", Value = "9 МБ", ProductId = 20 },
                new Characteristic { Id = 114, Name = "Cтандарт пам'яті", Value = "DDR4 2666 мгц", ProductId = 20 },
                new Characteristic { Id = 115, Name = "Частота процесора", Value = "3.7-4.6 ГГц", ProductId = 20 },
                new Characteristic { Id = 116, Name = "Модель", Value = "Prime B360M-K", ProductId = 21 },
                new Characteristic { Id = 117, Name = "Тип роз'єму для процесора", Value = "LGA1151", ProductId = 21 },
                new Characteristic { Id = 118, Name = "Частота пам'яті (звичайний режим), до", Value = "2666 МГц", ProductId = 21 },
                new Characteristic { Id = 119, Name = "Максимальний об'єм пам'яті", Value = "32 ГБ", ProductId = 21 },
                new Characteristic { Id = 120, Name = "Кількість слотів пам'яті", Value = "2", ProductId = 21 },
                new Characteristic { Id = 121, Name = "Чіпсет", Value = "Intel B360", ProductId = 21 },
                new Characteristic { Id = 122, Name = "Модель", Value = "B450M DS3H", ProductId = 22 },
                new Characteristic { Id = 123, Name = "Тип роз'єму для процесора", Value = "AM4", ProductId = 22 },
                new Characteristic { Id = 124, Name = "Частота пам'яті (звичайний режим), до", Value = "2933 МГц", ProductId = 22 },
                new Characteristic { Id = 125, Name = "Максимальний об'єм пам'яті", Value = "64 ГБ", ProductId = 22 },
                new Characteristic { Id = 126, Name = "Кількість слотів пам'яті", Value = "4", ProductId = 22 },
                new Characteristic { Id = 127, Name = "Чіпсет", Value = "AMD B450", ProductId = 22 },
                new Characteristic { Id = 128, Name = "Модель", Value = "TUF Gaming X570-Plus", ProductId = 23 },
                new Characteristic { Id = 129, Name = "Тип роз'єму для процесора", Value = "AM4", ProductId = 23 },
                new Characteristic { Id = 130, Name = "Частота пам'яті (звичайний режим), до", Value = "	2933 МГц", ProductId = 23 },
                new Characteristic { Id = 131, Name = "Максимальний об'єм пам'яті", Value = "	128 ГБ", ProductId = 23 },
                new Characteristic { Id = 132, Name = "Кількість слотів пам'яті", Value = "4", ProductId = 23 },
                new Characteristic { Id = 133, Name = "Чіпсет", Value = "AMD X570", ProductId = 23 },
                new Characteristic { Id = 134, Name = "Модель", Value = "X570 Master", ProductId = 24 },
                new Characteristic { Id = 135, Name = "Тип роз'єму для процесора", Value = "AM4", ProductId = 24 },
                new Characteristic { Id = 136, Name = "Частота пам'яті (звичайний режим), до", Value = "3200 мгц", ProductId = 24 },
                new Characteristic { Id = 137, Name = "Максимальний об'єм пам'яті", Value = "128 ГБ", ProductId = 24 },
                new Characteristic { Id = 138, Name = "Кількість слотів пам'яті", Value = "4", ProductId = 24 },
                new Characteristic { Id = 139, Name = "Чіпсет", Value = "AMD X570", ProductId = 24 },
                new Characteristic { Id = 140, Name = "Модель", Value = "	Prime H410M-A", ProductId = 25 },
                new Characteristic { Id = 141, Name = "Тип роз'єму для процесора", Value = "LGA1200", ProductId = 25 },
                new Characteristic { Id = 142, Name = "Частота пам'яті (звичайний режим), до", Value = "2933 МГц", ProductId = 25 },
                new Characteristic { Id = 143, Name = "Максимальний об'єм пам'яті", Value = "64 ГБ", ProductId = 25 },
                new Characteristic { Id = 144, Name = "Кількість слотів пам'яті", Value = "2", ProductId = 25 },
                new Characteristic { Id = 145, Name = "Чіпсет", Value = "Intel H410", ProductId = 25 },
                new Characteristic { Id = 146, Name = "Графічний чіп", Value = "GeForce RTX 3080", ProductId = 26 },
                new Characteristic { Id = 147, Name = "Інтерфейс", Value = "PCI Express x16 4.0", ProductId = 26 },
                new Characteristic { Id = 148, Name = "Об'єм пам'яті", Value = "10 ГБ", ProductId = 26 },
                new Characteristic { Id = 149, Name = "Тип пам'яті", Value = "GDDR6X", ProductId = 26 },
                new Characteristic { Id = 150, Name = "Макс. частота ядра", Value = "	1710 МГц", ProductId = 26 },
                new Characteristic { Id = 151, Name = "Техпроцес", Value = "8 нм", ProductId = 26 },
                new Characteristic { Id = 152, Name = "Графічний чіп", Value = "GeForce RTX 3060 Ti", ProductId = 27 },
                new Characteristic { Id = 153, Name = "Інтерфейс", Value = "PCI Express x16 4.0", ProductId = 27 },
                new Characteristic { Id = 154, Name = "Об'єм пам'яті", Value = "8 ГБ", ProductId = 27 },
                new Characteristic { Id = 155, Name = "Тип пам'яті", Value = "GDDR6", ProductId = 27 },
                new Characteristic { Id = 156, Name = "Макс. частота ядра", Value = "1845 МГц", ProductId = 27 },
                new Characteristic { Id = 157, Name = "Техпроцес", Value = "8 нм", ProductId = 27 },
                new Characteristic { Id = 158, Name = "Графічний чіп", Value = "GeForce RTX 3060 Ti", ProductId = 28 },
                new Characteristic { Id = 159, Name = "Інтерфейс", Value = "PCI Express x16 4.0", ProductId = 28 },
                new Characteristic { Id = 160, Name = "Об'єм пам'яті", Value = "8 ГБ", ProductId = 28 },
                new Characteristic { Id = 161, Name = "Тип пам'яті", Value = "GDDR6", ProductId = 28 },
                new Characteristic { Id = 162, Name = "Макс. частота ядра", Value = "1740 МГц", ProductId = 28 },
                new Characteristic { Id = 163, Name = "Техпроцес", Value = "8 нм", ProductId = 28 },
                new Characteristic { Id = 164, Name = "Графічний чіп", Value = "GeForce RTX 3080", ProductId = 29 },
                new Characteristic { Id = 165, Name = "Інтерфейс", Value = "PCI Express x16 4.0", ProductId = 29 },
                new Characteristic { Id = 166, Name = "Об'єм пам'яті", Value = "10 ГБ", ProductId = 29 },
                new Characteristic { Id = 167, Name = "Тип пам'яті", Value = "GDDR6X", ProductId = 29 },
                new Characteristic { Id = 168, Name = "Макс. частота ядра", Value = "	1905 МГц", ProductId = 29 },
                new Characteristic { Id = 169, Name = "Техпроцес", Value = "8 нм", ProductId = 29 },
                new Characteristic { Id = 170, Name = "Графічний чіп", Value = "GeForce RTX 3060 Ti", ProductId = 30 },
                new Characteristic { Id = 171, Name = "Інтерфейс", Value = "PCI Express x16 4.0", ProductId = 30 },
                new Characteristic { Id = 172, Name = "Об'єм пам'яті", Value = "8 ГБ", ProductId = 30 },
                new Characteristic { Id = 173, Name = "Тип пам'яті", Value = "GDDR6", ProductId = 30 },
                new Characteristic { Id = 174, Name = "Макс. частота ядра", Value = "1740 МГц", ProductId = 30 },
                new Characteristic { Id = 175, Name = "Техпроцес", Value = "8 нм", ProductId = 30 },
                new Characteristic { Id = 176, Name = "Форм-фактор та тип пам'яті", Value = "DIMM DDR4", ProductId = 31 },
                new Characteristic { Id = 177, Name = "Об'єм пам'яті", Value = "16 ГБ", ProductId = 31 },
                new Characteristic { Id = 178, Name = "Кількість модулів в комплекті", Value = "2 × 8 ГБ", ProductId = 31 },
                new Characteristic { Id = 179, Name = "Тактова частота", Value = "3000 МГц", ProductId = 31 },
                new Characteristic { Id = 180, Name = "Форм-фактор та тип пам'яті", Value = "DIMM DDR4", ProductId = 32 },
                new Characteristic { Id = 181, Name = "Об'єм пам'яті", Value = "16 ГБ", ProductId = 32 },
                new Characteristic { Id = 182, Name = "Кількість модулів в комплекті", Value = "1 × 16 ГБ", ProductId = 32 },
                new Characteristic { Id = 183, Name = "Тактова частота", Value = "2666 МГц", ProductId = 32 },
                new Characteristic { Id = 184, Name = "Форм-фактор та тип пам'яті", Value = "DIMM DDR4", ProductId = 33 },
                new Characteristic { Id = 185, Name = "Об'єм пам'яті", Value = "16 ГБ", ProductId = 33 },
                new Characteristic { Id = 186, Name = "Кількість модулів в комплекті", Value = "1 × 16 ГБ", ProductId = 33 },
                new Characteristic { Id = 187, Name = "Тактова частота", Value = "3000 МГц", ProductId = 33 },
                new Characteristic { Id = 188, Name = "Форм-фактор та тип пам'яті", Value = "DIMM DDR4", ProductId = 34 },
                new Characteristic { Id = 189, Name = "Об'єм пам'яті", Value = "16 ГБ", ProductId = 34 },
                new Characteristic { Id = 190, Name = "Кількість модулів в комплекті", Value = "1 × 16 ГБ", ProductId = 34 },
                new Characteristic { Id = 191, Name = "Тактова частота", Value = "3200 МГц", ProductId = 34 },
                new Characteristic { Id = 192, Name = "Форм-фактор та тип пам'яті", Value = "DIMM DDR4", ProductId = 35 },
                new Characteristic { Id = 193, Name = "Об'єм пам'яті", Value = "32 ГБ", ProductId = 35 },
                new Characteristic { Id = 194, Name = "Кількість модулів в комплекті", Value = "2 × 16 ГБ", ProductId = 35 },
                new Characteristic { Id = 195, Name = "Тактова частота", Value = "3200 МГц", ProductId = 35 },
                new Characteristic { Id = 196, Name = "Діагональ екрану", Value = "23.5", ProductId = 36 },
                new Characteristic { Id = 197, Name = "Максимальна роздільна здатність", Value = "1920 × 1080", ProductId = 36 },
                new Characteristic { Id = 198, Name = "Співвідношення сторін", Value = "16:9", ProductId = 36 },
                new Characteristic { Id = 199, Name = "Тип матриці", Value = "PLS", ProductId = 36 },
                new Characteristic { Id = 200, Name = "Час відгуку", Value = "4 мс", ProductId = 36 },
                new Characteristic { Id = 201, Name = "Діагональ екрану", Value = "23.8", ProductId = 37 },
                new Characteristic { Id = 202, Name = "Максимальна роздільна здатність", Value = "1920 × 1080", ProductId = 37 },
                new Characteristic { Id = 203, Name = "Співвідношення сторін", Value = "16:9", ProductId = 37 },
                new Characteristic { Id = 204, Name = "Тип матриці", Value = "IPS", ProductId = 37 },
                new Characteristic { Id = 205, Name = "Час відгуку", Value = "5 мс", ProductId = 37 },
                new Characteristic { Id = 206, Name = "Діагональ екрану", Value = "23.8", ProductId = 38 },
                new Characteristic { Id = 207, Name = "Максимальна роздільна здатність", Value = "1920 × 1080", ProductId = 38 },
                new Characteristic { Id = 208, Name = "Співвідношення сторін", Value = "16:9", ProductId = 38 },
                new Characteristic { Id = 209, Name = "Тип матриці", Value = "IPS", ProductId = 38 },
                new Characteristic { Id = 210, Name = "Час відгуку", Value = "5 мс", ProductId = 38 },
                new Characteristic { Id = 211, Name = "Діагональ екрану", Value = "27", ProductId = 39 },
                new Characteristic { Id = 212, Name = "Максимальна роздільна здатність", Value = "2560 × 1440", ProductId = 39 },
                new Characteristic { Id = 213, Name = "Співвідношення сторін", Value = "16:9", ProductId = 39 },
                new Characteristic { Id = 214, Name = "Тип матриці", Value = "IPS", ProductId = 39 },
                new Characteristic { Id = 215, Name = "Час відгуку", Value = "5 мс", ProductId = 39 },
                new Characteristic { Id = 216, Name = "Діагональ екрану", Value = "23.8", ProductId = 40 },
                new Characteristic { Id = 217, Name = "Максимальна роздільна здатність", Value = "1920 × 1080", ProductId = 40 },
                new Characteristic { Id = 218, Name = "Співвідношення сторін", Value = "16:9", ProductId = 40 },
                new Characteristic { Id = 219, Name = "Тип матриці", Value = "IPS", ProductId = 40 },
                new Characteristic { Id = 220, Name = "Час відгуку", Value = "1 мс", ProductId = 40 },
                new Characteristic { Id = 221, Name = "Інтерфейс підключення", Value = "USB", ProductId = 41 },
                new Characteristic { Id = 222, Name = "Цифровий блок", Value = "є", ProductId = 41 },
                new Characteristic { Id = 223, Name = "Механізм клавіш", Value = "мембранний", ProductId = 41 },
                new Characteristic { Id = 224, Name = "Інтерфейс підключення", Value = "USB", ProductId = 42 },
                new Characteristic { Id = 225, Name = "Цифровий блок", Value = "є", ProductId = 42 },
                new Characteristic { Id = 226, Name = "Механізм клавіш", Value = "мембранний", ProductId = 42 },
                new Characteristic { Id = 227, Name = "Інтерфейс підключення", Value = "USB", ProductId = 43 },
                new Characteristic { Id = 228, Name = "Цифровий блок", Value = "є", ProductId = 43 },
                new Characteristic { Id = 229, Name = "Механізм клавіш", Value = "мембранний", ProductId = 43 },
                new Characteristic { Id = 230, Name = "Інтерфейс підключення", Value = "радіоканал", ProductId = 44 },
                new Characteristic { Id = 231, Name = "Цифровий блок", Value = "є", ProductId = 44 },
                new Characteristic { Id = 232, Name = "Механізм клавіш", Value = "мембранний", ProductId = 44 },
                new Characteristic { Id = 233, Name = "Інтерфейс підключення", Value = "USB", ProductId = 45 },
                new Characteristic { Id = 234, Name = "Цифровий блок", Value = "є", ProductId = 45 },
                new Characteristic { Id = 235, Name = "Механізм клавіш", Value = "мембранний", ProductId = 45 },
                new Characteristic { Id = 236, Name = "Підключення", Value = "бездротове", ProductId = 46 },
                new Characteristic { Id = 237, Name = "Тип сенсора", Value = "лазерний", ProductId = 46 },
                new Characteristic { Id = 238, Name = "Роздільна здатність сенсора", Value = "540 dpi", ProductId = 46 },
                new Characteristic { Id = 239, Name = "Підключення", Value = "дротове", ProductId = 47 },
                new Characteristic { Id = 240, Name = "Тип сенсора", Value = "оптичний", ProductId = 47 },
                new Characteristic { Id = 241, Name = "Роздільна здатність сенсора", Value = "1000 dpi", ProductId = 47 },
                new Characteristic { Id = 242, Name = "Підключення", Value = "бездротове", ProductId = 48 },
                new Characteristic { Id = 243, Name = "Тип сенсора", Value = "оптичний", ProductId = 48 },
                new Characteristic { Id = 244, Name = "Роздільна здатність сенсора", Value = "1000 dpi", ProductId = 48 },
                new Characteristic { Id = 245, Name = "Підключення", Value = "дротове", ProductId = 49 },
                new Characteristic { Id = 246, Name = "Тип сенсора", Value = "оптичний", ProductId = 49 },
                new Characteristic { Id = 247, Name = "Роздільна здатність сенсора", Value = "800 dpi", ProductId = 49 },
                new Characteristic { Id = 248, Name = "Підключення", Value = "дротове", ProductId = 50 },
                new Characteristic { Id = 249, Name = "Тип сенсора", Value = "оптичний", ProductId = 50 },
                new Characteristic { Id = 250, Name = "Роздільна здатність сенсора", Value = "1000 dpi", ProductId = 50 },
                new Characteristic { Id = 251, Name = "Процесор", Value = "Apple A14 Bionic (6-ядерный 1.8-3.1 ГГц)", ProductId = 51 },
                new Characteristic { Id = 252, Name = "Кількість ядер процесора", Value = "6", ProductId = 51 },
                new Characteristic { Id = 253, Name = "Розмір дисплея", Value = "6.7", ProductId = 51 },
                new Characteristic { Id = 254, Name = "Роздільна здатність дисплея", Value = "2778 × 1284 (Quad HD+)", ProductId = 51 },
                new Characteristic { Id = 255, Name = "Процесор", Value = "Apple A14 Bionic (6-ядерный 1.8-3.1 ГГц)", ProductId = 52 },
                new Characteristic { Id = 256, Name = "Кількість ядер процесора", Value = "6", ProductId = 52 },
                new Characteristic { Id = 257, Name = "Розмір дисплея", Value = "6.7", ProductId = 52 },
                new Characteristic { Id = 258, Name = "Роздільна здатність дисплея", Value = "2778 × 1284 (Quad HD+)", ProductId = 52 },
                new Characteristic { Id = 259, Name = "Процесор", Value = "Qualcomm Snapdragon 732G SM7150-AC (2x2.3 GHz Cortex-A76 & 6x1.8 GHz Cortex-A55)", ProductId = 53 },
                new Characteristic { Id = 260, Name = "Кількість ядер процесора", Value = "8", ProductId = 53 },
                new Characteristic { Id = 261, Name = "Розмір дисплея", Value = "6.55", ProductId = 53 },
                new Characteristic { Id = 262, Name = "Роздільна здатність дисплея", Value = "6.55", ProductId = 53 },
                new Characteristic { Id = 263, Name = "Процесор", Value = "Qualcomm Snapdragon 732G SM7150-AC (2x2.3 GHz Cortex-A76 & 6x1.8 GHz Cortex-A55)", ProductId = 54 },
                new Characteristic { Id = 264, Name = "Кількість ядер процесора", Value = "8", ProductId = 54 },
                new Characteristic { Id = 265, Name = "Розмір дисплея", Value = "6.67", ProductId = 54 },
                new Characteristic { Id = 266, Name = "Роздільна здатність дисплея", Value = "2400 × 1080 (Full HD+)", ProductId = 54 },
                new Characteristic { Id = 267, Name = "Процесор", Value = "Unisoc SC9863A (4x1.6 GHz Cortex-A55 & 4x1.2 GHz Cortex-A55)", ProductId = 55 },
                new Characteristic { Id = 268, Name = "Кількість ядер процесора", Value = "8", ProductId = 55 },
                new Characteristic { Id = 269, Name = "Розмір дисплея", Value = "6.52", ProductId = 55 },
                new Characteristic { Id = 270, Name = "Роздільна здатність дисплея", Value = "1600 × 720 (HD+)", ProductId = 55 },
                new Characteristic { Id = 271, Name = "Стандарти зв'язку", Value = "GSM 850/900/1800/1900", ProductId = 56 },
                new Characteristic { Id = 272, Name = "Підтримка повідомлень", Value = "SMS", ProductId = 56 },
                new Characteristic { Id = 273, Name = "Тип SIM-карти", Value = "Mini-SIM", ProductId = 56 },
                new Characteristic { Id = 274, Name = "Стандарти зв'язку", Value = "GSM 850/900/1800/1900", ProductId = 57 },
                new Characteristic { Id = 275, Name = "Підтримка повідомлень", Value = "MMS/SMS", ProductId = 57 },
                new Characteristic { Id = 276, Name = "Тип SIM-карти", Value = "Mini-SIM", ProductId = 57 },
                new Characteristic { Id = 277, Name = "Стандарти зв'язку", Value = "GSM 850/900/1800/1900", ProductId = 58 },
                new Characteristic { Id = 278, Name = "Підтримка повідомлень", Value = "MMS/SMS", ProductId = 58 },
                new Characteristic { Id = 279, Name = "Тип SIM-карти", Value = "Mini-SIM", ProductId = 58 },
                new Characteristic { Id = 280, Name = "Стандарти зв'язку", Value = "GSM 850/900/1800/1900", ProductId = 59 },
                new Characteristic { Id = 281, Name = "Підтримка повідомлень", Value = "MMS/SMS", ProductId = 59 },
                new Characteristic { Id = 282, Name = "Тип SIM-карти", Value = "Mini-SIM", ProductId = 59 },
                new Characteristic { Id = 283, Name = "Стандарти зв'язку", Value = "GSM 850/900/1800/1900", ProductId = 60 },
                new Characteristic { Id = 284, Name = "Підтримка повідомлень", Value = "SMS", ProductId = 60 },
                new Characteristic { Id = 285, Name = "Тип SIM-карти", Value = "Mini-SIM", ProductId = 60 },
                new Characteristic { Id = 286, Name = "Роз'єм 1", Value = "USB Type-A", ProductId = 61 },
                new Characteristic { Id = 287, Name = "Роз'єм 2", Value = "USB Type-A", ProductId = 61 },
                new Characteristic { Id = 288, Name = "Версія USB", Value = "2.0", ProductId = 61 },
                new Characteristic { Id = 289, Name = "Роз'єм 1", Value = "USB Type-A", ProductId = 62 },
                new Characteristic { Id = 290, Name = "Роз'єм 2", Value = "USB Type-A", ProductId = 62 },
                new Characteristic { Id = 291, Name = "Версія USB", Value = "3.0", ProductId = 62 },
                new Characteristic { Id = 292, Name = "Роз'єм 1", Value = "USB Type-A", ProductId = 63 },
                new Characteristic { Id = 293, Name = "Роз'єм 2", Value = "Apple Lightning", ProductId = 63 },
                new Characteristic { Id = 294, Name = "Версія USB", Value = "2.0", ProductId = 63 },
                new Characteristic { Id = 295, Name = "Роз'єм 1", Value = "USB Type-A", ProductId = 64 },
                new Characteristic { Id = 296, Name = "Роз'єм 2", Value = "Apple Lightning/USB Micro-B/USB Type-C", ProductId = 64 },
                new Characteristic { Id = 297, Name = "Довжина", Value = "1.2 м", ProductId = 64 },
                new Characteristic { Id = 298, Name = "Роз'єм 1", Value = "USB Type-A", ProductId = 65 },
                new Characteristic { Id = 299, Name = "Роз'єм 2", Value = "USB Type-C", ProductId = 65 },
                new Characteristic { Id = 300, Name = "Версія USB", Value = "2.0", ProductId = 65 }
            });

            base.OnModelCreating(builder);
        }
    }
}
